---
- hosts: all
  become: yes
  tasks:
  - name: Install openjdk 8
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tomcat 7
    yum:
      name: tomcat
      state: present
  - name: download jenkins to webapps folder
    get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.150.1/jenkins.war     
      dest: /user/share/tomcat/webapps/jenkins.war  
  - name:  enable and start tomcat 
    service:
      name: tomcat 
      states: started
      enabled: yes   
